[package]
name = "cargo-faasta"
version = "0.1.0"
edition = "2021"

[lib]
name = "cargo_faasta"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
tokio.workspace = true
serde_json.workspace = true
zip.workspace = true
reqwest = { version = "0.12.12", features = ["blocking", "stream", "multipart", "json"] }
walkdir = "2.5.0"
# removed dependency on faasta-analyze
clap = { version = "4", features = ["derive"] }
clap-cargo = "0.15.1"
indicatif = "0.17.11"
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
oauth2 = "4.4.2"
open = "5.0.1"
tiny_http = "0.12.0"
axum = "0.8.1"
libloading = "0.8"
cap-async-std = "3.4"
url = "2.5.0"
# Added for RPC functionality
faasta-interface = { path = "../interface" }
futures = "0.3.30"
s2n-quic = "1.36.0"
tarpc = { version = "0.36.0", features = ["tokio1", "serde1"] }
tracing = "0.1.40"

[dev-dependencies]
tempfile = "3.10.1"
assert_cmd = "2.0.14"
predicates = "3.1.0"
