[package]
name = "faasta-interface"
version = "0.2.0"
edition = "2021"
description = "bitrpc types for the faasta serverless platform"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
futures = "0.3"
dashmap = "6.0"
bytes = { version = "1.5", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
bincode = { version = "2", features = ["derive"] }
hyper = { version = "1.0", features = ["full"] }
bitrpc = { version = "0.2.0", features = ["compio-server"] }
http = "1.0"
bitcode = { version = "0.6", features = ["derive"] }
